import { test, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { installPilotWorkspace, workspaceFixture } from "../fixtures/workspace-session";

test.use({ trace: "off", screenshot: "off" });
test("CORE06: buyer, mobile supplier and operator conversation workflow", async ({ page, browser }) => {
  const db = new PrismaClient();
  const supplierContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const operatorContext = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const supplierPage = await supplierContext.newPage(), operatorPage = await operatorContext.newPage();
  for (const surface of [page, supplierPage, operatorPage]) surface.setDefaultTimeout(15_000);
  const rights = ["support.ticket.view", "support.ticket.create", "notification.view"];
  const buyer = await installPilotWorkspace(page, "BUYER", rights);
  const supplier = await installPilotWorkspace(supplierPage, "SUPPLIER", rights);
  const key = randomUUID();
  let operatorId: string | undefined;
  try {
    await page.setViewportSize({ width: 1440, height: 900 });
    const offer = await db.supplierOffer.findFirstOrThrow({ where: { supplierOrganizationId: supplier.organizationId, status: "ACTIVE", publication: { status: "PUBLISHED", marketplaceVisible: true }, conversations: { none: { buyerOrganizationId: buyer.organizationId } } } });
    const org = await db.organization.create({ data: { bin: `95${String(Date.now()).slice(-10)}`, legalName: `Core06 ${key}`, displayName: "Synthetic operator", capabilities: { create: { capability: "MARKETPLACE_OPERATOR" } } } });
    const user = await db.user.create({ data: { email: `core06-${key}@example.invalid`, displayName: "Synthetic operator", emailVerifiedAt: new Date() } }); operatorId = user.id;
    const role = await db.role.create({ data: { organizationId: org.id, code: "operator", name: "Оператор", permissions: { create: [...rights, "support.ticket.manage", "organization.view", "catalog.product.view"].map(code => ({ permission: { connect: { code } } })) } } });
    await db.organizationMembership.create({ data: { userId: user.id, organizationId: org.id, status: "ACTIVE", roles: { create: { roleId: role.id } } } });
    const session = await workspaceFixture(db, "MARKETPLACE_OPERATOR", { userId: user.id, organizationId: org.id, displayName: org.displayName });
    await operatorPage.addInitScript(({ session, actorId }) => sessionStorage.setItem("dentmarket_admin_session", JSON.stringify({ ...session, actorId, user: { id: actorId }, activeOrganizationId: session.organizationId })), { session, actorId: user.id });
    await page.goto(`/clinic/messages?contextType=OFFER&contextId=${offer.id}`);
    const chat = page.getByRole("region", { name: "Сообщения", exact: true });
    await chat.getByLabel("Сообщение", { exact: true }).fill(`Вопрос покупателя ${key}`);
    await chat.getByRole("button", { name: "Отправить", exact: true }).focus(); await page.keyboard.press("Enter");
    await expect(chat.getByRole("list", { name: "История сообщений" }).getByText(`Вопрос покупателя ${key}`)).toBeVisible();
    const conversation = await db.businessConversation.findFirstOrThrow({ where: { contextId: offer.id, buyerOrganizationId: buyer.organizationId, supplierOrganizationId: supplier.organizationId } });
    await supplierPage.goto(`/supplier/messages?conversationId=${conversation.id}`);
    const supplierChat = supplierPage.getByRole("region", { name: "Сообщения", exact: true });
    await expect(supplierChat.getByText(`Вопрос покупателя ${key}`, { exact: true }).last()).toBeVisible();
    await supplierChat.getByLabel("Сообщение", { exact: true }).fill(`Ответ поставщика ${key}`);
    let failSend = true;
    await supplierPage.route(`**/conversations/${conversation.id}/messages`, async route => { if (failSend) { failSend = false; await route.abort("failed"); } else await route.continue(); });
    await supplierChat.getByRole("button", { name: "Отправить", exact: true }).click();
    await expect(supplierChat.getByRole("alert")).toBeVisible();
    await expect(supplierChat.getByLabel("Сообщение", { exact: true })).toHaveValue(`Ответ поставщика ${key}`);
    await supplierChat.getByRole("button", { name: "Отправить", exact: true }).click();
    await expect(supplierChat.getByRole("list", { name: "История сообщений" }).getByText(`Ответ поставщика ${key}`)).toBeVisible();
    expect(await db.conversationMessage.count({ where: { conversationId: conversation.id, body: `Ответ поставщика ${key}` } })).toBe(1);
    await supplierPage.screenshot({ path: test.info().outputPath("conversation-supplier-390.png"), fullPage: true });
    expect(await supplierPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await chat.getByRole("button", { name: "Обновить", exact: true }).click();
    await expect(chat.getByRole("list", { name: "История сообщений" }).getByText(`Ответ поставщика ${key}`)).toBeVisible();
    await chat.getByRole("button", { name: "Вопрос решён", exact: true }).click();
    await expect(chat.getByText("Вопрос решён. Новое сообщение откроет его снова.")).toBeVisible();
    await chat.getByRole("button", { name: "Обратиться к оператору" }).click();
    await chat.getByLabel("Причина обращения (не менее 10 символов)").fill(`Нужна помощь оператора ${key}`);
    await chat.getByRole("button", { name: "Создать обращение" }).click();
    await expect(chat.getByText("К диалогу подключён оператор площадки.")).toBeVisible();
    await operatorPage.goto("/admin?section=overview");
    const queue = operatorPage.getByRole("region", { name: "Операционная очередь" });
    const assignmentOpener = queue.getByRole("button", { name: "Назначение и история" }).first();
    await assignmentOpener.focus(); await operatorPage.keyboard.press("Enter");
    await expect(operatorPage.getByRole("dialog")).toBeVisible();
    await operatorPage.keyboard.press("Escape");
    await expect(operatorPage.getByRole("dialog")).toBeHidden();
    await expect(assignmentOpener).toBeFocused();
    await operatorPage.goto("/admin?section=support");
    const support = operatorPage.getByRole("region", { name: "Обращения и диалоги" });
    await expect(support).toBeVisible();
    const updated = await db.businessConversation.findUniqueOrThrow({ where: { id: conversation.id } });
    const ticket = await db.supportTicket.findUniqueOrThrow({ where: { id: updated.supportTicketId! } });
    const opener = support.getByRole("article").filter({ hasText: ticket.number }).getByRole("button", { name: "Открыть обращение" });
    await opener.focus(); await operatorPage.keyboard.press("Enter");
    const dialog = operatorPage.getByRole("dialog");
    await expect(dialog).toBeVisible();
    await operatorPage.keyboard.press("Escape");
    await expect(dialog).toBeHidden();
    await expect(opener).toBeFocused();
    await operatorPage.keyboard.press("Enter");
    await dialog.getByLabel("Ответственный", { exact: true }).selectOption(user.id);
    await dialog.getByLabel("Причина изменения").fill("Назначение ответственного по обращению");
    await dialog.getByRole("button", { name: "Сохранить решение" }).click();
    await expect(dialog.getByText("Изменение обращения сохранено.")).toBeVisible();
    await dialog.getByRole("button", { name: "Открыть связанный диалог" }).click();
    await expect(support).toBeFocused();
    const operatorChat = operatorPage.getByRole("region", { name: "Сообщения", exact: true });
    await operatorChat.getByLabel("Сообщение", { exact: true }).fill(`Ответ оператора ${key}`);
    await operatorChat.getByRole("button", { name: "Отправить", exact: true }).click();
    await expect(operatorChat.getByRole("list", { name: "История сообщений" }).getByText(`Ответ оператора ${key}`)).toBeVisible();
    await operatorPage.screenshot({ path: test.info().outputPath("conversation-operator-1440.png"), fullPage: true });
    await chat.getByRole("button", { name: "Обновить", exact: true }).click();
    await expect(chat.getByRole("listitem").filter({ hasText: `Ответ оператора ${key}` }).getByText("Synthetic operator · Оператор площадки")).toBeVisible();
    await page.screenshot({ path: test.info().outputPath("conversation-buyer-1440.png"), fullPage: true });
    await supplierPage.goto("/supplier/support");
    await supplierPage.getByLabel("Тема", { exact: true }).fill(`Обращение ${key}`);
    await supplierPage.getByLabel("Описание", { exact: true }).fill("Проверка создания обращения поставщиком");
    await supplierPage.getByRole("button", { name: "Создать обращение", exact: true }).click();
    await expect(supplierPage.getByText("Обращение создано.")).toBeVisible();
    expect(await supplierPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  } catch (error) {
    console.log("CORE06 operator accessibility", await operatorPage.evaluate(() => {
      const panel = document.querySelector('section[aria-label="Сообщения"]');
      const textarea = panel?.querySelector("textarea");
      const hiddenAncestors: string[] = [];
      for (let node = textarea as Element | null; node; node = node.parentElement) if (node.getAttribute("aria-hidden") === "true" || node.hasAttribute("inert")) hiddenAncestors.push(node.tagName);
      return { panelPresent: Boolean(panel), inputPresent: Boolean(textarea), inputId: textarea?.id, labels: Array.from(panel?.querySelectorAll("label") ?? []).map(label => ({ text: label.textContent, for: label.htmlFor })), hiddenAncestors };
    }).catch(() => null));
    await operatorPage.screenshot({ path: test.info().outputPath("operator-failure.png"), fullPage: true }).catch(() => {});
    throw error;
  } finally {
    await Promise.allSettled([page.goto("about:blank"), supplierContext.close(), operatorContext.close()]);
    await buyer.dispose(); await supplier.dispose();
    if (operatorId) await db.authSession.updateMany({ where: { userId: operatorId }, data: { status: "REVOKED", revokedAt: new Date(), revokeReason: "core06_browser_finished" } });
    await db.$disconnect();
  }
});
