import { expect, test } from "@playwright/test";
import { offerPromotionFixture } from "../fixtures/offer-promotion";

for (const width of [1366, 390]) test(`real promotion moderation and gift checkout at ${width}px`, async ({ page, request }, testInfo) => {
  const fixture = await offerPromotionFixture();
  const { db, supplier, buyer, operator, main, gift } = fixture;
  await page.setViewportSize({ width, height: 900 });
  await page.addInitScript(({ supplier, buyer, operator }) => {
    sessionStorage.setItem("dentmarket:supplier-session", JSON.stringify(supplier));
    sessionStorage.setItem("dentmarket:buyer-session", JSON.stringify(buyer));
    sessionStorage.setItem("dentmarket_admin_session", JSON.stringify(operator));
  }, { supplier, buyer, operator });
  const name = `Подарок к покупке ${fixture.key.slice(0, 8)}`;
  try {
    await page.goto("/supplier/products/promotions");
    const create = page.getByRole("button", { name: "Новая акция", exact: true });
    await create.focus(); await expect(create).toBeFocused(); await page.keyboard.press("Enter");
    await page.getByLabel("Поиск: Товар акции", { exact: true }).fill(main.name);
    await page.getByRole("button", { name: "Найти: Товар акции", exact: true }).click();
    await page.getByRole("combobox", { name: "Товар акции", exact: true }).selectOption(main.id);
    await page.getByRole("textbox", { name: "Название акции", exact: true }).fill(name);
    await page.getByLabel("Механика", { exact: true }).selectOption("BUY_X_GET_Y");
    await page.getByRole("textbox", { name: "Количество покупки N", exact: true }).fill("5");
    await page.getByLabel("Поиск: Подарок", { exact: true }).fill(gift.name);
    await page.getByRole("button", { name: "Найти: Подарок", exact: true }).click();
    await page.getByRole("combobox", { name: "Подарок", exact: true }).selectOption(gift.id);
    await page.getByRole("textbox", { name: "Количество подарка M", exact: true }).fill("2");
    await page.getByRole("button", { name: "Сохранить черновик", exact: true }).click();
    await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Согласовать версию", exact: true })).toHaveCount(0);
    await page.getByRole("button", { name: "Отправить на согласование", exact: true }).click();
    await expect(page.locator("strong").filter({ hasText: /^На проверке$/ })).toBeVisible();
    const p = await db.promotion.findFirstOrThrow({ where: { supplierOrganizationId: supplier.organizationId, name } });
    const denied = await request.post(`http://127.0.0.1:4012/api/promotions/${p.id}/commands`, { headers: { authorization: `Bearer ${supplier.accessToken}` }, data: { action: "APPROVE", reason: "Self approval must fail", expectedVersion: p.version, idempotencyKey: `deny-${fixture.key}` } });
    expect(denied.status()).toBe(403);
    const hidden = await request.get(`http://127.0.0.1:4012/api/promotions/storefront?q=${encodeURIComponent(name)}`);
    expect(hidden.status()).toBe(200); expect((await hidden.json()).items).toHaveLength(0);
    await page.goto("/admin?section=catalog");
    if (width < 760) await page.getByRole("combobox", { name: "Раздел админки", exact: true }).selectOption("catalog");
    else await page.getByRole("button", { name: "Каталог", exact: true }).click();
    await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
    await expect(page.getByText(/Минимум за последние 30 дней/)).toBeVisible();
    await page.getByRole("textbox", { name: "Причина решения", exact: true }).fill("Исходная цена и подарок проверены на тестовой акции");
    await page.getByRole("button", { name: "Согласовать версию", exact: true }).click();
    await expect(page.getByRole("button", { name: "Разместить на витрине", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Разместить на витрине", exact: true }).click();
    await expect(page.getByRole("button", { name: "Снять с витрины", exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath(`operator-${width}.png`), fullPage: true });
    await page.goto(`/promotions?q=${encodeURIComponent(name)}`);
    await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
    await expect(page.getByText(new RegExp(`подарок ${gift.name}`))).toBeVisible();
    await expect(page.getByRole("combobox", { name: "Категория", exact: true })).toBeVisible();
    await expect(page.getByRole("combobox", { name: "Поставщик", exact: true })).toBeVisible();
    await page.getByLabel("Механика", { exact: true }).selectOption("PERCENTAGE");
    await expect(page.getByText("Действующих акций нет", { exact: true })).toBeVisible();
    await page.goBack();
    await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath(`storefront-${width}.png`), fullPage: true });
    const headers = { authorization: `Bearer ${buyer.accessToken}` };
    const cartResponse = await request.post(`http://127.0.0.1:4012/api/buyers/${buyer.organizationId}/carts`, { headers, data: { currency: "KZT" } });
    expect(cartResponse.status()).toBe(201);
    const cart = await cartResponse.json();
    const line = await request.post(`http://127.0.0.1:4012/api/carts/${cart.id}/items`, { headers, data: { offerId: main.id, quantity: 10 } });
    expect(line.status()).toBe(201);
    await page.goto("/clinic/cart");
    await expect(page.getByText(new RegExp(`Подарок: ${gift.name} × 4`))).toBeVisible();
    await page.getByRole("button", { name: "Оформить заказ", exact: true }).click();
    await expect(page).toHaveURL(/\/clinic\/orders$/);
    const order = await db.supplierOrder.findFirstOrThrow({ where: { buyerOrganizationId: buyer.organizationId }, include: { items: true } });
    expect(order.items.filter(item => item.giftForItemId)).toHaveLength(1);
    await page.goto(`/clinic/orders/${order.id}`);
    await expect(page.getByText(/Обещанный подарок:/)).toBeVisible();
    await expect(page.getByText(/Подарок ·/)).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath(`gift-order-${width}.png`), fullPage: true });
  } finally { await fixture.dispose(); }
});
