import { createLightTheme, type BrandVariants, type Theme } from "@fluentui/react-components";
import contract from "./semantic-light.json";
import components from "./component-contract.json";

const t = contract.tokens;
// Fluent ramps run dark → light. Explicit semantic overrides below define
// interactive states; the ramp supplies the remaining decorative tokens.
const brand: BrandVariants = {
  10: "#00180F", 20: "#001E15", 30: "#00261B", 40: t["brand.pressed"],
  50: "#00543E", 60: t["brand.pressed"], 70: t["brand.hover"], 80: t["brand.default"],
  90: "#009F67", 100: "#1FBE7D", 110: t["brand.accent"], 120: "#87E3B8",
  130: t["brand.border"], 140: t["brand.border"], 150: t["brand.soft"], 160: t["brand.soft"],
};

export const dentMarketLightTheme: Theme = {
  ...createLightTheme(brand),
  fontFamilyBase: 'var(--font-sans, "Segoe UI"), ui-sans-serif, sans-serif',
  fontFamilyNumeric: 'var(--font-sans, "Segoe UI"), ui-sans-serif, sans-serif',
  fontFamilyMonospace: 'var(--dm-font-mono), monospace',
  borderRadiusMedium: components.tokens["--dm-radius-field"],
  borderRadiusLarge: components.tokens["--dm-radius-card"],
  colorNeutralForeground1: t["text.primary"],
  colorNeutralForeground2: t["text.secondary"],
  colorNeutralForeground3: t["text.muted"],
  colorNeutralForeground4: t["text.muted"],
  colorNeutralForegroundOnBrand: t["text.inverse"],
  colorNeutralForegroundDisabled: t["disabled.content"],
  colorNeutralBackground1: t["surface.default"],
  colorNeutralBackground1Hover: t["surface.hover"],
  colorNeutralBackground1Pressed: t["brand.soft"],
  colorNeutralBackground1Selected: t["brand.soft"],
  colorNeutralBackground2: t["surface.canvas"],
  colorNeutralBackground3: t["surface.subtle"],
  colorNeutralBackground4: t["surface.subtle"],
  colorNeutralBackgroundDisabled: t["disabled.surface"],
  colorNeutralStroke1: t["border.control"],
  colorNeutralStroke1Hover: t["brand.default"],
  colorNeutralStroke1Pressed: t["brand.pressed"],
  colorNeutralStroke2: t["border.default"],
  colorNeutralStroke3: t["border.default"],
  colorNeutralStrokeAccessible: t["border.control"],
  colorNeutralStrokeAccessibleHover: t["brand.hover"],
  colorNeutralStrokeAccessiblePressed: t["brand.pressed"],
  colorNeutralStrokeDisabled: t["disabled.border"],
  colorBrandBackground: t["brand.default"],
  colorBrandBackgroundHover: t["brand.hover"],
  colorBrandBackgroundPressed: t["brand.pressed"],
  colorBrandBackgroundSelected: t["brand.pressed"],
  colorBrandBackground2: t["brand.soft"],
  colorBrandBackground2Hover: t["brand.soft"],
  colorBrandBackground2Pressed: t["brand.border"],
  colorBrandForeground1: t["brand.content"],
  colorBrandForeground2: t["brand.content"],
  colorBrandForegroundLink: t["brand.content"],
  colorBrandForegroundLinkHover: t["brand.hover"],
  colorBrandForegroundLinkPressed: t["brand.pressed"],
  colorBrandForegroundLinkSelected: t["brand.content"],
  colorBrandStroke2: t["brand.border"],
  colorCompoundBrandBackground: t["brand.default"],
  colorCompoundBrandBackgroundHover: t["brand.hover"],
  colorCompoundBrandBackgroundPressed: t["brand.pressed"],
  colorCompoundBrandForeground1: t["brand.content"],
  colorCompoundBrandForeground1Hover: t["brand.hover"],
  colorCompoundBrandForeground1Pressed: t["brand.pressed"],
  colorSubtleBackgroundHover: t["surface.hover"],
  colorSubtleBackgroundPressed: t["brand.soft"],
  colorSubtleBackgroundSelected: t["brand.soft"],
  colorStrokeFocus1: t["surface.default"],
  colorStrokeFocus2: t["focus.ring"],
  colorStatusSuccessForeground1: t["success.content"],
  colorStatusSuccessBackground1: t["success.soft"],
  colorStatusWarningForeground1: t["warning.content"],
  colorStatusWarningBackground1: t["warning.soft"],
  colorStatusDangerForeground1: t["danger.content"],
  colorStatusDangerBackground1: t["danger.soft"],
  colorPaletteRedForeground1: t["danger.content"],
};
